#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  force_global_config = true

[[layers]]
  name = 'autocomplete'
  enable = false

[[custom_plugins]]
  name = 'derekwyatt/vim-scala'
  merged = 0

[[custom_plugins]]
  name = 'neoclide/coc.nvim'
  merged = 0
  build = 'sh -c ./install.sh'

